### ISSUE TITLE
Language array issues

### ISSUE THREAD

**Issue by seancarew** [JoomFish/joomfish-2.5#132]
I started with a clean J2.5.8 site and installed the latest build from yesterday.

I installed languages.

They show in joomfish/content languages...I then tried to activate the languages and save.

I got the language array error...but a top few languages were now indicated as active.

I attempted to activate more languages...could not do so...same error.
![Joom-Fish--Control-Panel](https://f.cloud.github.com/assets/36703/89147/832af1bc-6523-11e2-9794-e5c1f1bd5eff.png)
![Joom-Fish--Joom-Fish-Language-Manager](https://f.cloud.github.com/assets/36703/89148/86e45fb4-6523-11e2-988f-327d5d7cd8b4.png)

**Comment by akempkens** [comment]
Can you sent me a backup of your site? I looks like a quite complex one and good test environment.

Alex

Am 23.01.2013 um 07:10 schrieb Sean Carew notifications@github.com:

**Comment by seancarew** [comment]
Sure - no problem.  I will send you an installer which has sample content...you can re-create my base site...please send me an email address

**Comment by klas** [comment]
I went for bug hunting (using trial&error method as nothing else worked )on sandbox site that you sent me -> issue is caused by multiple english languages you have installed. Unfortunately Joomfish won't work with multiple languages with the same iso short code, it works on presumption each language is  represented only once.

To resolve this you will need to uninstall duplicate english language and truncate  #_jf_languages_ext table

**Comment by akempkens** [comment]
Klas do you think we should implement a save check to avoid this happening?

**Comment by seancarew** [comment]
That would be a good idea.  I am still not sure what I did to cause the error...perhaps a safety net.

**Comment by akempkens** [comment]
I tested about 5 existing and non existing languages now. The issue should not occur anymore

**Comment by seancarew** [comment]
Thanks very much Alex  - sent via Hojoki
