### ISSUE TITLE
Native vs Joomfish Translation handling - pros and cons

### ISSUE THREAD

**Issue by GeraintEdwards** [JoomFish/joomfish-2.5#36]
Reviewing where we are I think there a re couple of issues we should discuss relating to  native/joomfish translation handling.  

If you are not familiar with the distinction then look at the content.xml file we set the <treatment><target> to native - this means that the translation of Joomla content items is (by default) stored in the Joomla content table using the native language flag AND a Joomfish mapping table which links the translation to the original.    If this treatment was 'joomfish' (or not specified) we would be using the old Joomfish approach of storing the translations in the jf_content table with a separate row per field translated.

The main advantage of the native approach is performance and filtering/ordering of lists (e.g.  you get the list of content items ordered by the translation title and not the order of the originals etc).

However it could lead to confusion since if the original article is set to display in all languages and it is translated into one specific language (e.g. german)  then you will currently see this item appear twice in the frontend.  The content component gets articles with language = german or \* then Joomfish translates the \* version so you end up with 2 identical german articles.

This problem can be addressed in 2 ways:
1.  Tell users that they must specify a language for the original items instead of using 'All languages' (i.e. *) .  Or 
2. Use the Joomfish translation approacj

Any thoughts?

**Comment by quodo** [comment]
Summary: currently I prefer the JoomFish approach and not the new native approach. (_Sorry to say it, thinking about the time you guys must have spent implementing a new approach..._)

Last week I started to translate the sample data, content element by content element, just to see where the issues were (no, not nearly finished yet) and get an idea of how "usable" Joomfish 2.5 alpha currently is.

I had the same question Geraint poses here, but then for Categories...

That made me realise that not only content articles are saved in Joomla content table (and no longer in a seperate Joomfish table) but also categories. At first I thought it was wonderfull, but then I was wondering if this would be the best approach. Right now it appears to be complicated to keep track of all the "original" articles when viewing what articles are available in Joomla (which include the translations made with Joomfish). I find it overwhelming at the moment (I do realise that it might "just" be something to adapt to).

Also, I wonder what happens with the assets for permissions. For articles, which are at the bottom of the hierarchy in permission (global permissions > component permissions > category permissions > article permissions), it's sort of alright: they keep the same parent assest, but when the asset for the original language is changed, does the asset for the translated article change as well, or be tracked as different?

For categories it's worse (in my mind) concerning assets. Which assets do they inherit their permissions from and from which asset to translated children inherit permissions?

Now back to your question.
If you were asking what to do with category translations, I'd say please don't use native, use joomfish. I'd prefer to setup a website in one language and then translate everything into a second language. Added to that Joomla now allows you to setup menu items or contents only for the second language as well, so that might be a good option for content that I wouldn't want in my first language. The "native" way is too complicated for me.

For content, currently I'd be happier with the way JoomFish on Joomla 1.5 handles things, e.g. the Joomfish approach instead of the native approach (_while realising that this could just be an emotion of not being used to the new native approache and it's advantages?!_). I'd say it's possibilities are less overwhelming and users already know it from experience in Joomla 1.5.

Regarding option 1.
Currently, if you have an article that has the language set to the main language (e.g. not all but english) and you switch to the second language (e.g. dutch) the article does not show when the language is switched to the second language with the module. That's as I expected. However, I still would like to see all of my articles even when untranslated, preferably with a little note saying the article is not translated yet. Easy solution, just set the language to "all", but isn't that besides the current point? _Hmmm, what is my point here...?_

Perhaps an option number 3:
Would it be easy to implement an option for the user to let joomfish behave the "joomfish" or the "native" way (based on what I just learned from Geraint, I'd hack the content element to say joomfish instead of native)? On component level per content element, or on item level, e.g. per article, category, etc.? Or would that make things really worse?

I'd love to read other people's thoughs on this too!

**Comment by klas** [comment]
I would say while it certainly adds a level of complexity to the code it will perform better - we only need to provide a way to workaround such issues (perhaps something simple like adding unique to the query will sufficce ? ) - one general principle perhaps would be to tell users to either use core language features OR joomfish, but not both at the same time (e.g. this all languages/one language distinction is a good example) as they way have different operational logic and since tusers must also use corresponding language selector in the frontend. For the backend we can override language choices selector and remove "all languages" option in the article (so that user is forced to select language or keep default one).

**Comment by klas** [comment]
I have added experimental overrides plugin that removes "All languages" option from interface, if we decide to take other route we can remove it later. Probably we also need to add sdome sort of query to change language for existing items and/or possibly change content queries to treat all languages items the same as they were set to default language

**Comment by MStruller** [comment]
I prefer the native,
but i see problems:

<pre>we must find a way for the user to see where is the original 
and where the tranlated in all of the used components/extensions.</pre>
<pre>usage of menus where are home/featured is strong, 
here we must found a way to make an new menutype if we translate 
because only one item can be home/featured in one menuttype</pre>
<pre>we must find an way to generall filter the language 
(as the default from the user or the default from the system?) 
in components/extensions because 
if we have translated native, in the joomla we have a lot of items</pre>
<pre>we must find an way to set/copy the permissions if any changes here 
in the item see the comment from Quodo</pre>
<pre>we need an flag to set if need the item an translation so we can 
display an 'not translated' in the frontend
or we must usage the all(*) to set an item where we not want to translate
</pre>

<pre>must remove the usage of all(*)???? see the comment from Klas.</pre>

**Comment by klas** [comment]
Just a note about my commit - I added it so we can better test removal of "all option" effects, to get back to previous behavior simply unpublish overrides plugin.

**Comment by klas** [comment]
Also installer had some errors, so use latest revision

**Comment by quodo** [comment]
There might be a different list on pros and cons for different components (or (core) Content Elements).

For categories and menus there are, for me, disadvantages that perhaps don't hold for content articles. I get lost in how to use JoomFish with its new native way of translating as soon as "an item" can have/has "children" (think of categories and menus). 

Think of this scenario (for menu items):

In the Sample data there is a menu-module "About Joomla" with menu items "Getting Started", "Using Joomla!", etc. The menu item "Using Joomla!" (with id 280 and parent_id 1) has submenu items: 
- "Using Extensions" (id 277, parent_id 280)
- "Parameters" (id 453, Parent_id 280)
- "Getting Help" (id 436, parent_id 280)

Translating the menu item "Using Joomla!" to "Using Joomla! - NL" creates a new menu item, with (for me) id 521 and parent_id 1. However, the submenu items of its en-GB counterpart are no longer shown (as they have parent_id 280 and not 521).

This is where I (currently) would rather see the JoomFish way of translating instead of the native way (at least for menus anyway). Why? I find the beauty of JoomFish to be that I can create a site in one language and translate every bit from articles to menu items, etc. and keep the same structure. This seems lost, to me, now.
Or is there a way to keep the submenu-items tied to the menu item I translated?

Perhaps I should no longer use the idea of a complete site in one language and content translated in the same structure. Perhaps I'd have to think of it of creating one site in one language and another site in a second language. By that I mean that I have to have different menu items / menu modules for each language. Then the content in the first language can be an example for the second language and I'd translate content like a menu-item and be able to assign a different parent menu item for my translation. So, I'd need to expand the Content Element for menus to include the Parent Item dropdown list.

When I can translate the Parent Item of a menu item I'd assign to corrent "Using Joomla"-translation to my "Parameters" submenu-item-translation. I'd then be creating Menu items more in the Joomla 2.5 way (but would I need/want JoomFish for that?).

Hmmm, I'm struggling on how I should use JoomFish in Joomla 2.5.

**Comment by MStruller** [comment]
about quodos last comment

an scenario
we have menu items:
'parent' id 2
->'child' id 3
first we translate the 'parent' (will save in the translationmap) as id 4
second we translate the 'child' (also save in translationmap) as id 5
the 'child' have parent_id 2 on save we will have an look to the translationmap if the parent with id 2 translated
and if so we can get the new parent_id from the translationmap and save the 'child' with the new parent_id

if the user will translate first the 'child' i think we can make to look similar
i think it will not be easy to code the functionality for that but it can coded.

for categories we can make the same.

in the joomla-core we have no association in joomfish we have association.

i think quodos comments are right but not for the question native/joomfish save

**Comment by quodo** [comment]
About Klas' jfoverrides plugin:
In this thread http://www.joomfish.net/forum/viewtopic.php?f=48&t=11186&p=38144#p38144 there is a jf-future user who can assign the "JF Language Selection" module only for one language (he included a screenshot). He needs to create a module for each language now. 

Could this be a disadvantage of the experimental jfoverrides plugin Klas created? _(I haven't tested it myself yet)_

**Comment by klas** [comment]
Plugin goal is to make the whole Joomla behave in Joomfish way, so that the same as in 1.5. version default language (usually en-GB) behaves the same as "All languages" in core Joomla 2.5. - in a way that default language is shown when there is no translation. So it is correct that there is no All option anymore, but assigning it to "e-Gb" or whatever default site language should create the same result, if not this is a bug.

**Comment by MStruller** [comment]
I think **jfoverrides** is not the right way,
if the user make an translation from an *(All) item joomfish must make an alert/confirm to set the *(All) item to the default language or an other language where the user can select

**Comment by quodo** [comment]
I've just uninstalled JoomFish (everything, including module and plugins) and then installed jf-future where the last commit was 853aa344e0 (on Joomla 2.5.1).

Then I change this in the "JF Language Selection" module (nothing else)
- Position set to position-0 (Search position in template beez_20)
- Status set to Published
- Module Assignment (in Menu Assignment) to "On all pages"
- Language set to English (choice of three: English en-GB, Dutch nl-NL and French fr-FR)
  --> As soon as I click the dutch or french flag (raw display of images) the module does not show. **According to Klas (https://github.com/JoomFish/jf-future/issues/36#issuecomment-4344085) this is then a bug/unwanted feature.**

With the new "Joomfish - Core overrides" pugin disabled I can set the Language of the module to All and the module shows in any language.

The Details in the Module Manager for "JF Language Selection" change if the override plugin is enabled/disabled:
- Language: "All" choice is removed
- new: "Is Translation" (No/Yes)
- new: "translation of :" (user can enter a number, 0 by default)
- new: "original id :" (user can enter a number, 99 by default)
- new: "new id :" (user can enter a number, 99 by default)

I find this an interesting idea: with already translated contents (article "Beginners" in the sample contents) I can see that 
- Language = Dutch
- Is Translation? = Yes
- translation of : = 8 (correct: id of the original)
- original id : = 75 (confusing name: it is the id of the current article, e.g. the translation)
- new id : = 75 (confusing name: why is it "new"?)

J!1.5 with JoomFish shows the article of the default language when it's not available in the other languages. This override plugin does not do that, it limits the article to the default language.

However, I like the idea of this override plugin, but perhaps it's better to keep the "All" option in the Language dropdown but call it something like "Default language and languages for wich a translation is unavailable". That way you have the "old" J!1.5+JF behaviour combined with the new J!2.5 feature that a user can have content for only one specific language (default or other).

**Comment by klas** [comment]
User can either use Joomfish or core translation system, he can't use both as they work in different ways and have different internal logic. Joomfish has language a to b language translations maping, while core system is just filtering and this 2 systems are just incompatible and trying to bend them to work together will result in never ending logical traps and bugs. See Geraints first post for example of such incompatibility. Also in such mixed case native and joomfish translation systems used in joomfish 2.5. would then work in different ways, leading to even greater confusion.

Now, alternative option is to keep core joomla approach, but then joomfish turns into an extension of that system, no more than a fancy management system for core.

**Comment by MStruller** [comment]
the simplest way for the *(ALL):
in joomfish deaktivate the edit from *(ALL) (only give the users an note that *(ALL) can not translate)
in the joomla components deaktivate (over  jfoverrides ) the language select only if there are translations
so then the user can not change the language

**Comment by caniggia** [comment]
How I see this and how it started working for me yesterday.

I have similar problem, but my is different, I have default language PL and I do translation to EN,
but unfortunatly all articels by default are set english, so joomla is getting crazy.
If I change my default articles to PL, it's also not working. 

It works well if I do set all default oryginal PL artictes to "All" language", but it gets me crazy because I can't do that for eg when I create new article, or save he makes default EN, but there's option bottom to reasign to all for many at once.

When I started translation, all articles were ALL language.

After change original to ALL, then it works.

Finally to not change language everytime after reading this thread, I disabled jfoverrides, so I have all language option again, and now everything works perfect for now.

I my opinion default language should have All languages - then when something is not translated I get original text (unfortunatelly I can't set fallback, but now I don't need this). This way for me is more clear.
Many people are translating page after some time, they by default have all set in every document.

Just removing experimental plugin makes it OK.

**Comment by alainroger** [comment]
working with j1.5 and j2.5, i have to say that the former way joomfish holds translation was much more better from my point of view.
it was clearer, with no risk to modify or delete a duplicated item.
it was simpler in the way that you had side-by-side, original and translation, so in case of modifying parameters you saw everything at once.

sorry to say that...

**Comment by ad0wk** [comment]
Ok, here's my tuppence.

There are some places where the language 'All' is needed. E.g. Joomla! needs to have a default menu item assigned to language 'All'. Without having the option to choose language 'All' you can't change that item. 

I can also see a lot of confusion arising from alternative and mutually exlusive ways of handling translations. E.g. if somebody creates some content from the front-end and assigns that to language 'All' it's impossible to assign it to any other another language because you can't change the alias once the article is saved. When you change it in the backend, you need to assign it to some language other than 'All'. Further, if Joomla! language filtering is off, that article ('assigned' to a specific language) is still showing in all other languages as well. How to deliver that info to the users?

Confused? Me, too. Then again, I'm just a graphic designer with practically no experience in coding. However I'm a relatively long-time JoomFish user and regardless of my background never needed any help with it. That's how intuitive and easy to use it has been for me. And I very much think and hope for myself and other more or less n00b users that this will be the case also in the future.
