### ISSUE TITLE
Create package installer

### ISSUE THREAD

**Issue by akempkens** [JoomFish/joomfish-2.5#6]
Create a package installer for the whole extension

**Comment by klas** [comment]
Done, please test. 

https://github.com/JoomFish/jf-future/commit/56fae2e54f32969edbd788558dc9620107279ad3

**Comment by quodo** [comment]
Tested
- downloaded zipfile from GitHub and installed it on a fresh Joomla 2.5.0
- downloaded the files from GitHub with git to a local directory and installed "from directory" on a fresh Joomla 2.5.0
  System: PHP 5.2.9, MySQL database 5.1.3, Apache 2.2.11, Mozilla Firefox 3.6, Directory Permissions: all Writable (green) (Xampp on Windows)

No errors and no problems for the installation, both work like a charm: component, module and plugins install fine.

The only thing making testing even more easy would be the "upgrade" method in the manifest instead of the "install" method, but I guess you don't want to do that if a lot of files are moved around? By the way, when I change the install method to upgrade, installation (or 'upgrade') works fine as well.

**Comment by klas** [comment]
Okm thnx, closing
